### ISSUE TITLE
unbuntu 系统下无法新建工程 一直卡着,不知是少了什么配置?

### ISSUE THREAD

**Issue by devsheng** [bravekingzhang/flutter_template_mason#1]
Loading options from /etc/masonrc...Check vars...ipchains was not found in your path or in /sbin. You may need to copy it
or add an explicit path to it in the following commands.
ipfwadm was not found in your path or in /sbin. You may need to copy it
or add an explicit path to it in the following commands.
Editor default of /usr/bin/vi taken.
Load IPs, networks and nameservers...Done.
---- Mason firewall builder for Linux                         ----
---- see http://www.pobox.com/~wstearns/mason/ for more info. ----
---- William Stearns <wstearns@pobox.com>                     ----
(This is release 1.0.0-11 - 2008-06-27 )

**Comment by bravekingzhang** [comment]
使用新的模板
